#pragma warning(disable : 4996)

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
#include<sys/stat.h>

void usage(const char *cmd, int st)
{
	fprintf(stderr, "Usage: %s <file-name> <output-file-name>", cmd);
	exit(st);
}

char *mk_var_prefix(const char *fname)
{
	char *prefix=strdup(fname);
	char *p=prefix;

	while(*p) {
		if(!isalnum(*p)) *p='_';
		++p;
	}
	if(!isalpha(*prefix)) *prefix='_';

	return prefix;
}

void mkcfile(const char *fname, const char *outfname)
{
	struct stat s;
	FILE *infp, *outfp;
	char *var_prefix=mk_var_prefix(fname);
	int ch;
	int first=1;

	if(!strcmp(outfname, "-")) outfp=stdout;
	else outfp=fopen(outfname, "w");

	if(!outfp) return;						/* TODO: Handle error */

	fprintf(outfp, "/* Generated by mkcfile */\n\n");
	fprintf(outfp, "#include<stdlib.h>\n\n");

	if(stat(fname, &s)==-1) return;			/* TODO: Handle error */

	fprintf(outfp, "size_t %s_len=%d;\n\n", var_prefix, s.st_size);

	fprintf(outfp, "unsigned char %s_data[]={\n", var_prefix);

	if(!(infp=fopen(fname, "rb"))) return;	/* TODO: Handle error */

	while((ch=getc(infp))!=EOF) {
		if(first) first=0;
		else fprintf(outfp, ",\n");

		fprintf(outfp, "\t%d", ch);
	}


	fprintf(outfp, "\n};\n\n");

	fclose(infp);
	if(outfp!=stdout) fclose(outfp);
}

int main(int argc, char *argv[])
{
	const char *fname="-", *outfname="-";

	if(argc>1) fname=argv[1];
	if(argc>2) outfname=argv[2];
	if(argc>3) usage(argv[0], EXIT_FAILURE);

	mkcfile(fname, outfname);

	return EXIT_SUCCESS;
}