
// Disable warning about deprecated functions in MSVC
#if defined(_MSC_VER)
#pragma warning(disable : 4996)
#endif

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
#include<sys/stat.h>

char *mystrdup(const char *s)
{
	char *ds;

	if(!(ds=(char *)malloc(strlen(s)+1))) return NULL;

	strcpy(ds, s);

	return ds;
}

void usage(const char *cmd, int st)
{
	fprintf(stderr, "Usage: %s <file-name> <output-file-name>", cmd);
	exit(st);
}

char *mk_var_prefix(const char *fname)
{
	char *prefix;
	char *p;

	if(!strcmp(fname, "-")) return mystrdup("stdin");
	else prefix=mystrdup(fname);

	p=prefix;

	while(*p) {
		if(!isalnum(*p)) *p='_';
		++p;
	}
	if(!isalpha(*prefix)) *prefix='_';

	return prefix;
}

void mkcfile(const char *fname, const char *outfname)
{
	FILE *infp, *outfp;
	char *var_prefix;
	int ch;
	int first=1;
	size_t size;

	if(!strcmp(outfname, "-")) outfp=stdout;
	else outfp=fopen(outfname, "w");

	if(!outfp) {
		fprintf(stderr, "ERROR: Unable to open output file %s\n", outfname);
		return;
	}

	fprintf(outfp, "/* Generated by mkcfile */\n\n");
	fprintf(outfp, "#include<stdlib.h>\n\n");

	if(!strcmp(fname, "-")) infp=stdin;
	else {
		if(!(infp=fopen(fname, "rb"))) {
			fprintf(stderr, "ERROR: Unable to open input file %s\n", fname);
			if(outfp!=stdout) fclose(outfp); 
			return;
		}
	}

	var_prefix=mk_var_prefix(fname);

	fprintf(outfp, "unsigned char %s_data[]={\n", var_prefix);

	size=0;
	while((ch=getc(infp))!=EOF) {
		if(first) first=0;
		else fprintf(outfp, ",\n");
		fprintf(outfp, "\t%d", ch);
		++size;
	}


	fprintf(outfp, "\n};\n\n");

	fprintf(outfp, "size_t %s_len=%lu;\n\n", var_prefix, (unsigned long)size);

	if(outfp!=stdout) fclose(outfp);
	if(infp!=stdin) fclose(infp);

	free(var_prefix);
}

int main(int argc, char *argv[])
{
	const char *fname="-", *outfname="-";

	if(argc>1) {
		if(!strcmp(argv[1], "-h") || !strcmp(argv[1], "--help")) usage(argv[0], EXIT_SUCCESS);
		fname=argv[1];
	}
	if(argc>2) outfname=argv[2];
	if(argc>3) usage(argv[0], EXIT_FAILURE);

	mkcfile(fname, outfname);

	return EXIT_SUCCESS;
}
